const types ={
    GET_POSTS : 'GET_POSTS',
    GET_POSTS_SUCCESS : 'GET_POSTS_SUCCESS',
    GET_POSTS_ERROR : 'GET_POSTS_ERROR',
    /* AUTH */
    POST_LOGIN : 'POST_LOGIN',
    POST_LOGIN_SUCCESS : 'POST_LOGIN_SUCCESS',
    POST_LOGIN_ERROR : 'POST_LOGIN_ERROR',
    SIGNUP: 'SIGNUP',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    REMOVE_ERROR: 'REMOVE_ERROR',
    LOGOUT: 'LOGOUT'

}

export default types